import React, { Fragment } from "react";
import PropTypes from "prop-types";
import { withStyles } from "@material-ui/core/styles";
import AppBar from "@material-ui/core/AppBar";
import Toolbar from "@material-ui/core/Toolbar";
import IconButton from "@material-ui/core/IconButton";
import Tooltip from "@material-ui/core/Tooltip";

const styles = theme => ({
  text: {
    paddingTop: theme.spacing.unit * 2,
    paddingLeft: theme.spacing.unit * 2,
    paddingRight: theme.spacing.unit * 2
  },
  paper: {
    paddingBottom: 50
  },
  list: {
    marginBottom: theme.spacing.unit * 2
  },
  subHeader: {
    backgroundColor: theme.palette.background.paper
  },
  appBar: {
    top: "auto",
    bottom: 60
  },
  toolbar: {
    alignItems: "center",
    justifyContent: "center"
  }
});

const messages = [
  {
    id: 1,
    primary: "Brunch this week?",
    secondary:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: "/static/images/avatar/5.jpg"
  },
  {
    id: 2,
    primary: "Birthday Gift",
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: "/static/images/avatar/1.jpg"
  },
  {
    id: 3,
    primary: "Recipe to try",
    secondary:
      "I am try out this new BBQ recipe, I think this might be amazing",
    person: "/static/images/avatar/2.jpg"
  },
  {
    id: 4,
    primary: "Yes!",
    secondary: "I have the tickets to the ReactConf for this year.",
    person: "/static/images/avatar/3.jpg"
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary:
      "My appointment for the doctor was rescheduled for next Saturday.",
    person: "/static/images/avatar/4.jpg"
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: "/static/images/avatar/5.jpg"
  },
  {
    id: 7,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: "/static/images/avatar/1.jpg"
  }
];

function About(props) {
  const { classes } = props;
  return (
    <React.Fragment>
      <AppBar
        position="fixed"
        className={classes.appBar}
        style={{ background: "transparent", boxShadow: "none" }}
      >
        <Toolbar className={classes.toolbar}>
          <Tooltip title="Email">
            <IconButton color="inherit">
              <span class="mdi mdi-email-outline" />
            </IconButton>
          </Tooltip>
          <Tooltip title="Linkedin">
            <a href="https://www.linkedin.com/in/meagan-lai-600822131/">
              <IconButton color="inherit">
                <span class="mdi mdi-linkedin" />
              </IconButton>
            </a>
          </Tooltip>
          <Tooltip title="Github">
            <a href="https://github.com/meagan-lai">
              <IconButton color="inherit">
                <span class="mdi mdi-github-circle" />
              </IconButton>
            </a>
          </Tooltip>
          <Tooltip title="Devpost">
            <a href="https://devpost.com/meaganlai">
              <IconButton color="inherit">
                <span class="mdi mdi-alpha-d-circle" />
              </IconButton>
            </a>
          </Tooltip>
        </Toolbar>
      </AppBar>
    </React.Fragment>
  );
}

About.propTypes = {
  classes: PropTypes.object.isRequired
};

export default withStyles(styles)(About);
